# _config.yml

theme: jekyll-theme-hacker

plugins:
  - jekyll-seo-tag
  - jemoji

title: DoodlePix - Diffusion based Drawing Assistant
description: Fidelity-controlled image generation from doodle inputs using a modified InstructPix2Pix framework. AKA Draw like a 5 years old and get great results!

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

include: ["README.md"]